# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02f0237f70d3d28d906e8c08c37593c30532b90ea20480dd6920bff77fb487abaf4b8c635f4a580c81cae0b745ab2b3af7632edb944ec32942e134ce36939f1

test:
  secret_key_base: b4214c3958064ad7fdd75f42500377e5404672e5c297560af2d01f1936bcd30a9eb2a5ed6f564301662c94918487f07c873f22c3349834ff5d9796314df8f00f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
